"""empty message

Revision ID: 3f1c9fbf2857
Revises: 431e8070ac75
Create Date: 2021-07-03 05:55:31.785832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1c9fbf2857'
down_revision = '431e8070ac75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist','looking_for_venues',new_column_name='seeking_venue') 
    op.alter_column('Venue','looking_for',new_column_name='seeking_talent') 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist','seeking_venue',new_column_name='looking_for_venues')
    op.alter_column('Venue','seeking_talent',new_column_name='looking_for')
    # ### end Alembic commands ###
