"""empty message

Revision ID: 5590f25a5ceb
Revises: 23c8a3352d68
Create Date: 2021-06-25 19:48:06.456810

"""
from sqlalchemy.sql.sqltypes import ARRAY
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5590f25a5ceb'
down_revision = '23c8a3352d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('looking_for_venues', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    #change tyoe of column genre from string to array of strings
    op.execute('ALTER TABLE "Artist" ALTER COLUMN genres TYPE VARCHAR(120)[] USING genres::character varying(120)[]')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'looking_for_venues')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
