"""empty message

Revision ID: f927338d7a89
Revises: 45250bb17ffb
Create Date: 2021-06-25 23:28:19.778267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f927338d7a89'
down_revision = '45250bb17ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_pkey',table_name='Show',type_='primary')
    op.add_column('Show', sa.Column('id', sa.Integer(), primary_key=True))
    op.execute('ALTER TABLE "Show" ADD CONSTRAINT Show_pkey PRIMARY KEY (id)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###
